[package]
name = "api"
version = "0.1.0"
authors = ["David Rojas <drojascamaggi@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-beta.3"
diesel = { version = "1.1.0", features = ["sqlite", "r2d2", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.9.0"
futures = "0.1.26"